
// This file has been generated by the GUI designer. Do not modify.
namespace NOTE
{
	public partial class NoteEditor
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Entry entryTitle;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewContent;
		private global::Gtk.Button buttonSave;
		private global::Gtk.HButtonBox hbuttonbox1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NOTE.NoteEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "NOTE.NoteEditor";
			// Container child NOTE.NoteEditor.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.entryTitle = new global::Gtk.Entry ();
			this.entryTitle.CanFocus = true;
			this.entryTitle.Name = "entryTitle";
			this.entryTitle.IsEditable = true;
			this.vbox4.Add (this.entryTitle);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entryTitle]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewContent = new global::Gtk.TextView ();
			this.textviewContent.CanFocus = true;
			this.textviewContent.Name = "textviewContent";
			this.GtkScrolledWindow.Add (this.textviewContent);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox4.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Save");
			this.vbox4.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonSave]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.vbox4.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox1]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.entryTitle.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnEntryTitleKeyPressEvent);
			this.textviewContent.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnTextviewContentKeyPressEvent);
			this.buttonSave.Released += new global::System.EventHandler (this.OnSave);
			this.buttonSave.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnButton1KeyPressEvent);
			this.buttonSave.Activated += new global::System.EventHandler (this.OnSave);
		}
	}
}
